### ISSUE TITLE
need help to start API

### ISSUE THREAD

**Issue by steffenxx** [Stay1444/iboardbot#1]
I am so happy that you have built a solution that allows us to use the iBoardBot again. I don't have a bug, but need a little help. I have started a Debian LCX on my Proxmox server and cloned your repository to /root/. I flashed the iBoardbot with the IP address of the Debian machine. That all worked but I can't get the API to start. I know a bit about Linux etc., but so far I have mostly used and configured ready-made installations. 1-2 lines would help me how to get the API running after cloning to the Debian machine. Ideally as a service with autostart. Thanks a lot

**Comment by Stay1444** [comment]
Yes! I'm really sorry about the lack of docs and in general and how unpolished everything is at the moment. I will try to improve the documentation, resources and usability in general in the following days.

What exactly is preventing the API from starting? Is it throwing any errors?

In any case, I pushed some docs on how to get it to work either manually, which is quite tedious, or using docker which is far easier. Check that out, and if there's anything that isn't working for you please reach out for help as many times as you want.

**Comment by steffenxx** [comment]
hi, I've already moved on :-) I have installed Rust and everything that goes with it, I was able to compile the binaries and ./iboardboard -port 8080 starts without errors. 

root@iboard:~/iboardbot/target/release# ./iboardbot --port 8080
2024-04-19T23:07:04.455502Z INFO iboardbot::api: Listening on 0.0.0.0:8080
2024-04-19T23:07:04.455532Z INFO iboardbot::api: API Docs available on http://0.0.0.0:8080/docs

The docs page on the server is accessible. :-)

I am currently struggling with the board itself. I can't reach the web interface to enter my new WLAN password.

I have seen that there is also a docker image. Does this work out of the box?

**Comment by Stay1444** [comment]
> The docs page on the server is accessible. :-)

Nice!

> I am currently struggling with the board itself. I can't reach the web interface to enter my new WLAN password.

I had the same issue with my board, when it doesn't find a wifi to connect to it's supposed to create a network called JJROBOTS where you can connect and then access a wifi config panel at http://196.168.4.1 but it always gives me connection refused. I just hard-coded  the WiFI credentials in the code and reflashed.

Edit `iBoardBot_114_M0.ino` and comment `readWifiConfig();` (line 103);
Then just below that add 

```cpp
strcpy(WifiConfig.pass, "password");
strcpy(WifiConfig.ssid, "ssid");
WifiConfig.status = 1;
WifiConfig.port = 80;
strcpy(WifiConfig.proxy, "");
```

> I have seen that there is also a docker image. Does this work out of the box?

The docker image does work out of the box. I recommend you check that out because you've got the API running but you are still missing the dependencies (text2svg and svg2gcode). You can install those manually as documented, if you want.

**Comment by steffenxx** [comment]
Great idea. I have adopted it, but it doesn't seem to work.

Here is the code from the sketch: 
(In my sketch, the line `readWifiConfig();` is line 104.)

`SerialUSB.println("Reading Wifi configuration...");
  //readWifiConfig();
  strcpy(WifiConfig.pass, „my_pw");
  strcpy(WifiConfig.ssid, „my_ssid");
  WifiConfig.status = 1;
  WifiConfig.port = 80;
  strcpy(WifiConfig.proxy, ""); `

**Comment by Stay1444** [comment]
Are you using the correct quotes (`"`)? In your comment there are some weird ones `„`. Also if your WiFI password contains any quotes, you'll have to escape them twice (one for the C++ code, another for the ESP to be able to parse it).

So if your password is `abc"2` you need to write 
```c
strcpy(WifiConfig.pass, "abc\\\"2");
``` 
 
If that's not it, then check out the Serial output from the board to see if it's complaining about something.

**Comment by steffenxx** [comment]
Ok, I'm not a developer, so I hadn't considered that :-O. My SSID contains a space. And my password exclamation marks

Something like that:

SSID: Word1 Word2
PW: !1234xxxxxxxx1234!

How do I have to enter this?

**Comment by Stay1444** [comment]
The space in the SSID might be a problem.

Can you verify that your WiFi network supports **2.4Ghz**? If it's only 5Ghz the ESP won't be able to connect to the WiFi.

If your WiFi's SSID is (for example) `Word1 Word2` you could try the following combinations, to see if they work.

Double `\` escaping the space:
```cpp
strcpy(WifiConfig.ssid, "Word1\\ Word2");
```

Using an URL encoded space:
```cpp
strcpy(WifiConfig.ssid, "Word1%20Word2");
```

Other characters that you might want to escape are `\`, `"` and `'`.
Seems that spaces on SSIDs are tricky for Arduinos / ESPs. 

- https://www.esp8266.com/viewtopic.php?p=76948
- https://esp32.com/viewtopic.php?t=10185
- https://www.reddit.com/r/esp8266/comments/uebkdi/esp_not_connecting_when_wifi_ssid_has_spaces/

**Comment by steffenxx** [comment]
I have tried all variants. The iBoardbot was already in my WLAN with the same SSID. And I have other ESP32 and ESP8266 boards running here. As ePaper drivers or to control BLE switchbots. I also tried to establish a connection to my guest wifi, which has a simple SSID and a simple password. All without special characters. So far all without success. 
By the way... I would like to thank you for your support.

**Comment by Stay1444** [comment]
> I have tried all variants. The iBoardbot was already in my WLAN with the same SSID. And I have other ESP32 and ESP8266 boards running here. As ePaper drivers or to control BLE switchbots. I also tried to establish a connection to my guest wifi, which has a simple SSID and a simple password.

That's weird then. I have no idea why it won't connect. To be fair the ibb code is kinda bad, since the wifi configuration panel doesn't even work. Have you checked the serial logs?

> I would like to thank you for your support.

Don't worry about it 🙂
I had to fight the thing a little bit too for it to work too.

**Comment by steffenxx** [comment]
One more thing. in the line `strcpy(WifiConfig.ssid, "Word1 Word2");` the word `Word1` is highlighted in brown. Only when I delete the space does the brown background disappear.

**Comment by steffenxx** [comment]
here are the logs:

```
readyServo init...
Reading Wifi configuration...
1
Word1 Word2
****

80


ERROR
AT+RST


OK

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 1856, room 16 
tail 0
chksum 0x63
load 0x3ffe8000, len 776, room 8 
tail 0
chksum 0x02
load 0x3ffe8310, len 552, room 8 
tail 0
chksum 0x79
csum 0x79

2nd boot version : 1.5
  SPI Speed      : 40MHz
  SPI Mode       : DIO
  SPI Flash Size & Map: 32Mbit(512KB+512KB)
jump to run user1 @ 1000

���|��rll�rll�rlr��b�b|b`�n�nlp��l�n��b�p��b�b
Ai-Thinker Technology Co. Ltd.

ready
```

**Comment by Stay1444** [comment]
> One more thing. in the line strcpy(WifiConfig.ssid, "Word1 Word2"); the word Word1 is highlighted in brown. Only when I delete the space does the brown background disappear.

Right, try with three `\`, like this
```c++
strcpy(WifiConfig.ssid, "Word1\\\ Word2");
```

I think that might solve the issue, since the logs look alright to me.

**Comment by steffenxx** [comment]
I tried it with a \. And apparently something has changed. When I send a request on the API server, this appears:

```
2024-04-20T17:20:16.777524Z  INFO iboardbot::api: Listening on 0.0.0.0:8080
2024-04-20T17:20:16.779036Z  INFO iboardbot::api: API Docs available on http://0.0.0.0:8080/docs
2024-04-20T17:55:03.179190Z  INFO iboardbot::api::services::boards: Board {boardId} connected
2024-04-20T17:55:03.180486Z  INFO iboardbot::api::services::boards: Created default board details for board {boardId} in boards/{boardId}.yaml
```

**Comment by Stay1444** [comment]
What did you name your board? did you change {boardId} for another thing when changing `Configuration.h`? The logs look fine besides that.

**Comment by Stay1444** [comment]
I recommend editing `./boards/{boardId}.yaml` (again, replace `{boardId}` with whatever you've named your board) and setting it's dimensions. For mine (the one shown on the readme), this works fine:
```yaml
dimensions:
    width: 3500
    height: 1000
```

**Comment by steffenxx** [comment]
I did not deliberately change the board name? Where do you do that.

**Comment by Stay1444** [comment]
> I did not deliberately change the board name? Where do you do that.

In `Configuration.h` you added this
```cpp
#define SERVER_HOST "0.0.0.0"
#define SERVER_URL "http://0.0.0.0:8080/_/board/main"
```

And `main` is = {boardId} but you probably have main there.
You mentioned that you sent a request to the server? 

Where the logs produced by the board connecting to the API or by your request?

In any case, running
```sh
$ curl --request GET \
  --url http://API_URL:8080/api/boards/
  ```
  Will tell you which boards are connected

**Comment by steffenxx** [comment]
I have changed exactly that in the `Configuration.h` 

```
#define SERVER_HOST "192.168.10.120"
#define SERVER_URL "http://192.168.10.120:8080/_/board/main"
``` 

When I send the request, this is what I get:

```
[
  {
    "available": [
      0,
      0,
      1000,
      1000
    ],
    "details": {
      "dimensions": {
        "height": 1000,
        "width": 1000
      }
    },
    "id": "ABC-MAIN",
    "last_update": "2024-04-20T18:23:05.077715828Z",
    "state": "ready"
  }
]
```

**Comment by Stay1444** [comment]
Seems that at some point the board connected. But judging by the `last_update` it was a while since it reached out. I would try restarting both the API and the board to see if they connect again. 

By the way, ive commited some quality of life stuff and improved the logging a bit, you might want to pull and rebuild.

**Comment by steffenxx** [comment]
I have seen that you have extended the documentation. I have now rebuilt the API on Docker.

**Comment by Stay1444** [comment]
Is everything working now? Should I close this?

**Comment by steffenxx** [comment]
No, I can't get the iBoard connected. I actually had contact once, but then never again.  

Is it correct that the iBoard always provides the internal JJROBOTS_IBB WLAN? Isn't that no longer needed if you configure the WLAN via the sketch?

**Comment by Stay1444** [comment]
In theory if you have the readWifiConfig(); line commented
```cpp
//readWifiConfig();
```

And then add all of the stuff below that (like you already did)
```cpp
  strcpy(WifiConfig.pass, "pass");
  strcpy(WifiConfig.ssid, "ssid");
  WifiConfig.status = 1;
  WifiConfig.port = 80;
  strcpy(WifiConfig.proxy, "");
```

It shouldn't create the JJROBOTS network since that's only for configuration.

**Comment by Stay1444** [comment]
Also, there's this line in the sketch
```cpp
  if (board_switch_pressed())
    writeWifiConfig(0, "", "", "", 0);
``` 
Which in theory resets the wifi config in the EEPROM when you press a switch on the board. We are not really using the EEPROM WifiConfig since we are hardcoding it, but you could press it to see if it changes anything.

**Comment by steffenxx** [comment]
Today I first changed my SSID, without spaces. That was a lot of work with over 40 devices connected to the WLAN. Many of them without a GUI. So with strange apps or ESP's via Arduino.

**Comment by Stay1444** [comment]
That really sounds like a pain :(

Let me know if that fixes your issue. The original Arduino code is quite bad. I'll do a bit of a rewrite because it needs it badly.

**Comment by steffenxx** [comment]
Unfortunately, it did not solve the problem. The JJROBOTS_IBB Wlan is always active and the iBoard cannot access the WLAN. A ./boards directory is not created either. 

Is it possible to send a ping to the board? 

It's totally strange because the board actually connected to the API once yesterday. 
I would be very happy if you could improve the code. And I hope you also get the "erasing" running.

**Comment by steffenxx** [comment]
One more question about the buttons. The board has 2 buttons. One on the side with the connections and one on the opposite side. Do you know the function?

**Comment by steffenxx** [comment]
In my sketch, the server URL is displayed as a link with an underscore. Could this be a problem?
![api_url](https://github.com/Stay1444/iboardbot/assets/42677304/063c191c-6d6d-4b17-9449-170485e24679)

**Comment by Stay1444** [comment]
> Unfortunately, it did not solve the problem. The JJROBOTS_IBB Wlan is always active and the iBoard cannot access the WLAN. A ./boards directory is not created either.

Yeah the wifi configuration mode is weird. It gets stuck sometimes. 

> Is it possible to send a ping to the board?

If it connects to your WLAN you could in theory see it in the DHCP leases page in your router. 

> One more question about the buttons. The board has 2 buttons. One on the side with the connections and one on the opposite side. Do you know the function?

I know one is for the wifi reset function. If you hold it while you power on the board it should completly reset the eeprom and the wifi configuration, that ofcourse for some reason only works sometimes. 

> In my sketch, the server URL is displayed as a link with an underscore. Could this be a problem?

It looks fine to me. The only thing different from my setup is that you are using port 8080 while im using port 80, so my configuration just doesn't add the port as 80 is the default for http. I don't think that's the problem but you could try with port 80.

**Comment by Stay1444** [comment]
Checking the firmware code, it won't work with other ports that aren't 80, as it completly disregards that and just connects to port 80 always, bummer. 

This really needs a rewrite.

**Comment by steffenxx** [comment]
I have changed everything to port 80, which is no problem. 
I have now connected a small TP-LINK WLAN access point with a very simple WLAN configuration to my network. The problem is clearly that the ibb is simply not logging into the WLAN. I just can't get it to do it. There must be something in the code that prevents it.

**Comment by Stay1444** [comment]
Ive updated the firmware and the documentation. Check out [this](https://github.com/Stay1444/iboardbot/blob/master/docs/Flash-Arduino.md).

**Comment by steffenxx** [comment]
With the new firmware, I can access the page via the Config Wlan and enter the data. The board then logs into the WLAN and the API server reports that a board is connected. So far it seems to be working.  Thank you very much.

I have noticed one thing. When the board reconnects, the ./boards/main.yaml is always recreated. This means that changes to the file are overwritten

**Comment by steffenxx** [comment]
Now I'm curious to see if I can get the iBoard working again. Maybe you can help me a little. Until now, I had controlled the iBoard via my home automation system (FHEM). I did this via an API call in the form:

`http://ibbapp.jjrobots.com/api/v1/text.php?APPID=xxxxxxxxxx&TEXT=".$z1."&X=20&Y=80&SIZE=3`

`$z1` is a variable with text.

What should an API call via your server look like?

**Comment by Stay1444** [comment]
> With the new firmware, I can access the page via the Config Wlan and enter the data. The board then logs into the WLAN and the API server reports that a board is connected. So far it seems to be working. Thank you very much.

Nice!

> I have noticed one thing. When the board reconnects, the ./boards/main.yaml is always recreated. This means that changes to the file are overwritten

I can't seem to replicate this issue

**Comment by Stay1444** [comment]
> Now I'm curious to see if I can get the iBoard working again. Maybe you can help me a little. Until now, I had controlled the iBoard via my home automation system (FHEM). I did this via an API call in the form:
> 
> `http://ibbapp.jjrobots.com/api/v1/text.php?APPID=xxxxxxxxxx&TEXT=".$z1."&X=20&Y=80&SIZE=3`
> 
> `$z1` is a variable with text.
> 
> What should an API call via your server look like?

I don't really know how FHEM works since i've never used it, but in theory you should be able to send a POST request to 

`http://localhost:8080/api/boards/jobs/__BOARDID__`
- Replace localhost with your API url
- Replace the port with your API port
- Replace `__BOARDID__` with your board Id (probably main)

And in the JSON body you should send

```json
{ 
    "WriteText": { 
        "text": "$z1" 
    } 
}
```

Where `$z1` is the text. 

The API doesn't really deal with positioning so the X,Y and size stuff is irrelevant. the text will fit on the board as it is resized to fit. 

The API will consider the space taken by the text as "used" and will not draw there ever again, until you queue the `Erase` job. **The erase job does not actually use the eraser to erase yet.**

**Comment by Stay1444** [comment]
In any case, since you have already solved the connection problems I'm gonna close this issue. If you want to get help with connecting your board to FHEM system please open an issue with that title so other people in the future can find it :)

**Comment by steffenxx** [comment]
All right, thank you very much.
